asset_path: /home/ryz5920/aut_unitree_g1_isaaclab/source/aut_unitree_g1_isaaclab/aut_unitree_g1_isaaclab/assets/flag/flag.gltf
usd_dir: /home/ryz5920/aut_unitree_g1_isaaclab/source/aut_unitree_g1_isaaclab/aut_unitree_g1_isaaclab/assets/flag
usd_file_name: flag.usd
force_usd_conversion: true
make_instanceable: true
mass_props:
  mass: 1.0
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexDecompositionCollisionAPI
  hull_vertex_limit: null
  max_convex_hulls: null
  min_thickness: null
  voxel_resolution: null
  error_percentage: null
  shrink_wrap: null
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2025-10-29 at 13:23:41.
##
